# ---
# The make file who contain all variables
# ---
include Makefile.cfg

# ---
# Tools variable
# ---

MKDIR := mkdir
RM := rm -f
ECHO := /usr/bin/echo

# ---
# Kernel variable
# ---

K_DIR := kernel/
K_BIN := kernel/vmkfs

# ---
# Distro variable
# ---

GRUB_CFG := tools/grub.cfg
ISO_ROOT_DIR := iso
ISO := kfsos.iso
