#!/bin/sh
cd "$(dirname $0)"


# ---
# Defaults variables
# ---

debug=
optimize=y
arch=i386
cflags=
ldflags=
asflags=

# ---
# Help message
# ---

usage() {
cat <<EOF
Usage: $0 [OPTION]
Defaults for the options are specified in brackets.
General options:
  --help                   display this help and exit
Build options:
  --debug                  enable debug mode
  --optimize-disable       disable optimization
  --arch=ARCH              set the target architecture (default: i386)
  --cflags=CFLAGS          some more compilation flags
  --ldflags=LDFLAGS        some more linker flags
  --asflags=LDFLAGS        some more assembler flags
Report bugs to ${maintainer}.
EOF
exit 0
}

# ---
# Check for help
# ---

for arg ; do case "$arg" in
--help|-h) usage ;;
esac; done


# ---
# Parse arguments
# ---

for arg ; do case "$arg" in
--debug) debug=y ;;
--optimize-disable) optimize= ;;
--arch=*) arch="${arg#*=}" ;;
--cflags=*) cflags="${arg#*=}" ;;
--ldflags=*) ldflags="${arg#*=}" ;;
--asflags=*) asflags="${arg#*=}" ;;
*) echo "Unknown option: ${arg#*=}";exit 1 ;;
esac; done

# ---
# Write Makefile.cfg
# ---

# Clean after

# make mrproper 1>/dev/null 2>/dev/null

# Write

exec 3>&1 1>Makefile.cfg
cat <<EOF
#!/usr/bin/make -f
#******************************************************************************#
# Makefile configuration generated by ./configure                              #
#******************************************************************************#
# Build options
DEBUG := $debug
OPTIMIZE := $optimize
ARCH := $arch
# Other tweaks
CMOREFLAGS := $cflags
LDMOREFLAGS := $ldflags
ASMOREFLAGS := $asflags
# End of file
EOF
exec 1>&3 3>&-

# Make it executable

chmod +x Makefile.cfg

# Print success message

echo "Configuration loaded, you can make now"

# End of file

