SUBDIRS += $(TOPDIR)/arch/i386/boot/ $(TOPDIR)/arch/i386/kernel/ $(TOPDIR)/arch/i386/devices/
K_OBJS += $(TOPDIR)/arch/i386/boot/boot.o $(TOPDIR)/arch/i386/kernel/kernel.o $(TOPDIR)/arch/i386/devices/devices.o

CPPFLAGS += -I$(TOPDIR)/arch/i386/include

K_LDSCRIPT := arch/i386/link.ld
